import Navbar from "@/components/Navbar";

import "@/css/common.css";

export const metadata = {
  title: "PokeBook",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
